/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as PredictionsAdminRouteImport } from './routes/predictions.admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminPredictionsRouteImport } from './routes/admin.predictions'
import { Route as ApiPredictionsJsonRouteImport } from './routes/api.predictions.json'

const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsAdminRoute = PredictionsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PredictionsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPredictionsJsonRoute = ApiPredictionsJsonRouteImport.update({
  id: '/api/predictions/json',
  path: '/api/predictions/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRouteWithChildren
  '/admin/predictions': typeof AdminPredictionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/predictions/admin': typeof PredictionsAdminRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/predictions/json': typeof ApiPredictionsJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRouteWithChildren
  '/admin/predictions': typeof AdminPredictionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/predictions/admin': typeof PredictionsAdminRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/admin': typeof AdminIndexRoute
  '/research': typeof ResearchIndexRoute
  '/api/predictions/json': typeof ApiPredictionsJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRouteWithChildren
  '/admin/predictions': typeof AdminPredictionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/predictions/admin': typeof PredictionsAdminRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/predictions/json': typeof ApiPredictionsJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/faq'
    | '/login'
    | '/predictions'
    | '/admin/predictions'
    | '/blog/$slug'
    | '/predictions/admin'
    | '/research/$slug'
    | '/admin/'
    | '/research/'
    | '/api/predictions/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/faq'
    | '/login'
    | '/predictions'
    | '/admin/predictions'
    | '/blog/$slug'
    | '/predictions/admin'
    | '/research/$slug'
    | '/admin'
    | '/research'
    | '/api/predictions/json'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/faq'
    | '/login'
    | '/predictions'
    | '/admin/predictions'
    | '/blog/$slug'
    | '/predictions/admin'
    | '/research/$slug'
    | '/admin/'
    | '/research/'
    | '/api/predictions/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRouteWithChildren
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ApiPredictionsJsonRoute: typeof ApiPredictionsJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions/admin': {
      id: '/predictions/admin'
      path: '/admin'
      fullPath: '/predictions/admin'
      preLoaderRoute: typeof PredictionsAdminRouteImport
      parentRoute: typeof PredictionsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/predictions/json': {
      id: '/api/predictions/json'
      path: '/api/predictions/json'
      fullPath: '/api/predictions/json'
      preLoaderRoute: typeof ApiPredictionsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PredictionsRouteChildren {
  PredictionsAdminRoute: typeof PredictionsAdminRoute
}

const PredictionsRouteChildren: PredictionsRouteChildren = {
  PredictionsAdminRoute: PredictionsAdminRoute,
}

const PredictionsRouteWithChildren = PredictionsRoute._addFileChildren(
  PredictionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRouteWithChildren,
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ApiPredictionsJsonRoute: ApiPredictionsJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
